In [2]:
import numpy as np

np.array([1,2,3])

array([1, 2, 3])

In [4]:
arr1=np.array(range(10))
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [8]:
arr2=np.array([0.1,0.2,0.3])
arr2

array([0.1, 0.2, 0.3])

In [9]:
arr3=np.array(['a','b','c'])
arr3

array(['a', 'b', 'c'], dtype='<U1')

In [10]:
arr4=np.array([1,2,'a','b',0.1,0.2])
arr4

array(['1', '2', 'a', 'b', '0.1', '0.2'], dtype='<U11')

In [12]:
arr5=np.array([1,2,0.3,0.4])
arr5

array([1. , 2. , 0.3, 0.4])

In [14]:
arr6=np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
arr6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## array의 타입

In [15]:
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [16]:
arr1.dtype

dtype('int32')

In [17]:
arr2.dtype

dtype('float64')

In [21]:
print(arr3.dtype)
arr3 # 문자열

<U1


array(['a', 'b', 'c'], dtype='<U1')

In [22]:
print(arr5.dtype)
arr5

float64


array([1. , 2. , 0.3, 0.4])

In [27]:
print(arr6.dtype)
arr6

int32


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

# shape

In [24]:
arr5

array([1. , 2. , 0.3, 0.4])

In [30]:
arr5.shape #길이가 4인 1차원 배열

(4,)

In [31]:
arr6


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
arr6.shape

(3, 3)

# arange, linspace

In [35]:
arr1=np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [36]:
arr2=np.arange(3,13)
arr2

array([ 3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [38]:
arr3=np.arange(5.0)
arr3

array([0., 1., 2., 3., 4.])

In [39]:
arr4=np.arange(3,100,3.0)
arr4

array([ 3.,  6.,  9., 12., 15., 18., 21., 24., 27., 30., 33., 36., 39.,
       42., 45., 48., 51., 54., 57., 60., 63., 66., 69., 72., 75., 78.,
       81., 84., 87., 90., 93., 96., 99.])

### linspace

In [40]:
np.linspace(-5,5,10)

array([-5.        , -3.88888889, -2.77777778, -1.66666667, -0.55555556,
        0.55555556,  1.66666667,  2.77777778,  3.88888889,  5.        ])

### reshape(배열의 형태 변환)

In [46]:
arr=np.arange(36.0)
arr

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [47]:
arr.shape

(36,)

In [51]:
arr2=arr.reshape(9,4)
arr2

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.],
       [24., 25., 26., 27.],
       [28., 29., 30., 31.],
       [32., 33., 34., 35.]])

In [53]:
# 3 dimension
arr3=arr.reshape(3,4,3)
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [56]:
print(arr1.shape)
arr1

(10,)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr1.shape=(5,2)
arr1

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [59]:
# -1 shape
print(arr3.shape)
arr3

(3, 4, 3)


array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.],
        [ 9., 10., 11.]],

       [[12., 13., 14.],
        [15., 16., 17.],
        [18., 19., 20.],
        [21., 22., 23.]],

       [[24., 25., 26.],
        [27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

In [64]:
arr3.reshape(-1,6) # -의 뜻 : 둘 중 한놈만 정해줄테니(12) 나머지는 니가 알아서 해줘

array([[ 0.,  1.,  2.,  3.,  4.,  5.],
       [ 6.,  7.,  8.,  9., 10., 11.],
       [12., 13., 14., 15., 16., 17.],
       [18., 19., 20., 21., 22., 23.],
       [24., 25., 26., 27., 28., 29.],
       [30., 31., 32., 33., 34., 35.]])

In [65]:
arr3.reshape(-1)

array([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.,
       13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23., 24., 25.,
       26., 27., 28., 29., 30., 31., 32., 33., 34., 35.])

In [66]:
arr3.reshape(4,-1,3)

array([[[ 0.,  1.,  2.],
        [ 3.,  4.,  5.],
        [ 6.,  7.,  8.]],

       [[ 9., 10., 11.],
        [12., 13., 14.],
        [15., 16., 17.]],

       [[18., 19., 20.],
        [21., 22., 23.],
        [24., 25., 26.]],

       [[27., 28., 29.],
        [30., 31., 32.],
        [33., 34., 35.]]])

# astype - 배열의 dtype 변환

In [68]:
arr1=np.arange(5)
arr2=np.arange(0.0, 0.5, 0.1)
arr1,arr2

(array([0, 1, 2, 3, 4]), array([0. , 0.1, 0.2, 0.3, 0.4]))

In [69]:
print(arr1.dtype)
print(arr2.dtype)

int32
float64


In [75]:
#int -> float
print(arr1.astype(float))
print(arr1.astype(np.float64))

[0. 1. 2. 3. 4.]
[0. 1. 2. 3. 4.]


In [78]:
# float -> char
print(arr2.astype(str))
print(arr2.astype(np.str))

['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']
['0.0' '0.1' '0.2' '0.30000000000000004' '0.4']


# random

In [79]:
np.random.rand(5)

array([0.01629239, 0.43714284, 0.13348766, 0.77481097, 0.00301223])

In [80]:
np.random.rand(3,3)

array([[0.6380096 , 0.05485956, 0.84516124],
       [0.5810717 , 0.26233231, 0.45127075],
       [0.31208979, 0.7359785 , 0.37906392]])

In [81]:
np.random.rand(2,2,2)

array([[[0.93494525, 0.661709  ],
        [0.14911895, 0.79918662]],

       [[0.85470356, 0.56336486],
        [0.697349  , 0.65704752]]])

## randint

In [86]:
np.random.randint(-5,10,(3,3))

array([[ 9,  3,  8],
       [ 4,  3,  4],
       [-1,  6, -5]])

In [276]:
np.random.randn(2,5)

array([[-0.15583999, -1.72229319,  0.09554278, -0.68022798, -1.60781505],
       [ 1.32269676, -0.33011195, -1.06427829,  1.56870543,  0.66101111]])

## array의 indexing, Slicing

In [95]:
arr1=np.arange(0,100,10.0)
print(arr1)
print(arr1.shape)

[ 0. 10. 20. 30. 40. 50. 60. 70. 80. 90.]
(10,)


In [98]:
arr1[2], arr1[-1]

(20.0, 90.0)

In [102]:
arr1[:3], arr1[4:], arr1[1:5]

(array([ 0., 10., 20.]),
 array([40., 50., 60., 70., 80., 90.]),
 array([10., 20., 30., 40.]))

In [103]:
arr1[::2],arr1[::3]

(array([ 0., 20., 40., 60., 80.]), array([ 0., 30., 60., 90.]))

## n-Dim Array Indexing, Slicing

In [113]:
# 2차원 배열 : 0~23, (8,3)의 배열을 만드세요. dtype=float
arr2=np.arange(24.0).reshape(8,3)
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [115]:
arr2[0], arr2[4]

(array([0., 1., 2.]), array([12., 13., 14.]))

In [120]:
print(arr2[3][1]) #성능이 느림 for문이 2번이라


print(arr2[3,1]) #성능이 빠름

10.0
10.0


In [123]:
print(arr2[3, 1:])

print(arr2[3:, 1:])

print(arr2[::2, :])

[10. 11.]
[[10. 11.]
 [13. 14.]
 [16. 17.]
 [19. 20.]
 [22. 23.]]
[[ 0.  1.  2.]
 [ 6.  7.  8.]
 [12. 13. 14.]
 [18. 19. 20.]]


In [126]:
arr2

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.],
       [ 9., 10., 11.],
       [12., 13., 14.],
       [15., 16., 17.],
       [18., 19., 20.],
       [21., 22., 23.]])

In [135]:
print(arr2[[0,5,3]])
print('--'*10)

print(arr2[[0,5,3],[2]])
print('--'*10)

[[ 0.  1.  2.]
 [15. 16. 17.]
 [ 9. 10. 11.]]
--------------------
[ 2. 17. 11.]
--------------------


In [136]:
arr2>10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [137]:
arr2[arr2>10]

array([11., 12., 13., 14., 15., 16., 17., 18., 19., 20., 21., 22., 23.])

In [139]:
arr2[arr2%2==1]

array([ 1.,  3.,  5.,  7.,  9., 11., 13., 15., 17., 19., 21., 23.])

### numpy의 상수

In [142]:
arr=np.array([1, 2, 3, np.nan, np.inf, -np.inf])
print("dtype : ", arr.dtype)
arr

dtype :  float64


array([  1.,   2.,   3.,  nan,  inf, -inf])

# arr의 연산

In [148]:
arr1=np.arange(0,10,1)
arr2=np.arange(1,0,-0.1)
arr1, arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]))

In [154]:
# array와 scalar 연산
print(arr1 + 1)
print(arr1+[1,1,1,1,1,1,1,1,1,1])

[ 1  2  3  4  5  6  7  8  9 10]
[ 1  2  3  4  5  6  7  8  9 10]


In [159]:
print(arr1-1)
print(arr1*2)
print(arr1/2)
print(arr1%2)
print(arr1**2)

[-1  0  1  2  3  4  5  6  7  8]
[ 0  2  4  6  8 10 12 14 16 18]
[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5]
[0 1 0 1 0 1 0 1 0 1]
[ 0  1  4  9 16 25 36 49 64 81]


In [160]:
arr1, arr2

(array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]),
 array([1. , 0.9, 0.8, 0.7, 0.6, 0.5, 0.4, 0.3, 0.2, 0.1]))

In [161]:
arr1+arr2

array([1. , 1.9, 2.8, 3.7, 4.6, 5.5, 6.4, 7.3, 8.2, 9.1])

In [162]:
arr1>5

array([False, False, False, False, False, False,  True,  True,  True,
        True])

In [163]:
arr1>arr2

array([False,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

## 행렬

In [164]:
# 0행렬
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [166]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

#### 일행렬

In [168]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [169]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

#### 단위행렬

In [171]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# 통계를 위한 연산

In [173]:
arr1=np.arange(1,11.0).reshape(5,2)
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

### sum

In [174]:
arr1.sum()

55.0

In [175]:
arr1.mean()

5.5

In [181]:
arr1.sum(axis=0)

array([25., 30.])

In [182]:
arr1.sum(axis=1)

array([ 3.,  7., 11., 15., 19.])

### mean

In [185]:
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [183]:
arr1.mean()

5.5

In [184]:
arr1.mean(axis=0)

array([5., 6.])

In [187]:
arr1.mean(axis=1)

array([1.5, 3.5, 5.5, 7.5, 9.5])

### var
#### 분산

In [188]:
arr1.var()

8.25

In [189]:
arr1.var(axis=0)

array([8., 8.])

In [190]:
arr1.var(axis=1)

array([0.25, 0.25, 0.25, 0.25, 0.25])

### std
#### 표준편차 = 분산 루트씌움

In [192]:
arr1.std()

2.8722813232690143

In [193]:
arr1.var(axis=0)

array([8., 8.])

In [194]:
arr1.var(axis=1)

array([0.25, 0.25, 0.25, 0.25, 0.25])

#### min

In [205]:
print(arr1.min())
print(arr1.min(axis=0))
print(arr1.min(axis=1))


1.0
[1. 2.]
[1. 3. 5. 7. 9.]


#### max

In [206]:
print(arr1.max())
print(arr1.max(axis=0))
print(arr1.max(axis=1))


10.0
[ 9. 10.]
[ 2.  4.  6.  8. 10.]


#### cumsum

In [207]:
arr1

array([[ 1.,  2.],
       [ 3.,  4.],
       [ 5.,  6.],
       [ 7.,  8.],
       [ 9., 10.]])

In [208]:
arr1.cumsum()

array([ 1.,  3.,  6., 10., 15., 21., 28., 36., 45., 55.])

In [209]:
arr1.cumsum(axis=0)

array([[ 1.,  2.],
       [ 4.,  6.],
       [ 9., 12.],
       [16., 20.],
       [25., 30.]])

In [210]:
arr1.cumsum(axis=1)

array([[ 1.,  3.],
       [ 3.,  7.],
       [ 5., 11.],
       [ 7., 15.],
       [ 9., 19.]])

#### cumprod

In [211]:
arr1.cumprod()

array([1.0000e+00, 2.0000e+00, 6.0000e+00, 2.4000e+01, 1.2000e+02,
       7.2000e+02, 5.0400e+03, 4.0320e+04, 3.6288e+05, 3.6288e+06])

In [212]:
arr1.cumprod(axis=0)

array([[1.00e+00, 2.00e+00],
       [3.00e+00, 8.00e+00],
       [1.50e+01, 4.80e+01],
       [1.05e+02, 3.84e+02],
       [9.45e+02, 3.84e+03]])

### sqrt, log, exp

In [199]:
np.sqrt(arr1.var(axis=1))

array([0.5, 0.5, 0.5, 0.5, 0.5])

In [200]:
np.log(arr1)

array([[0.        , 0.69314718],
       [1.09861229, 1.38629436],
       [1.60943791, 1.79175947],
       [1.94591015, 2.07944154],
       [2.19722458, 2.30258509]])

In [214]:
np.exp(arr1)

array([[2.71828183e+00, 7.38905610e+00],
       [2.00855369e+01, 5.45981500e+01],
       [1.48413159e+02, 4.03428793e+02],
       [1.09663316e+03, 2.98095799e+03],
       [8.10308393e+03, 2.20264658e+04]])

In [216]:
arr1=np.arange(1,7).astype(np.float64).reshape(2,3)
arr2=np.arange(6,0,-1.0).astype(np.float64).reshape(3,2)
arr1, arr2

(array([[1., 2., 3.],
        [4., 5., 6.]]),
 array([[6., 5.],
        [4., 3.],
        [2., 1.]]))

In [217]:
arr1.shape, arr2.shape

((2, 3), (3, 2))

In [219]:
arr1 @ arr2 # 행렬 곱

array([[20., 14.],
       [56., 41.]])

In [220]:
arr1.dot(arr2)

array([[20., 14.],
       [56., 41.]])

In [221]:
np.matmul(arr1, arr2)

array([[20., 14.],
       [56., 41.]])

### 전치

In [222]:
arr1

array([[1., 2., 3.],
       [4., 5., 6.]])

# 역행렬

In [224]:
arr1=np.arange(1,5).reshape(2,2)
arr1

array([[1, 2],
       [3, 4]])

In [226]:
arr2=np.linalg.inv(arr1) #역행렬
arr2

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [230]:
#단위행렬 나오니?
arr1.dot(arr2) 
#e-16은 0으로 봄

array([[1.00000000e+00, 1.11022302e-16],
       [0.00000000e+00, 1.00000000e+00]])

In [231]:
arr2.dot(arr1)

array([[1.0000000e+00, 4.4408921e-16],
       [0.0000000e+00, 1.0000000e+00]])

# concat

In [234]:
arr1=np.arange(4).reshape(2,2)
arr2=np.arange(0,40,10).reshape(2,2)
arr1, arr2

(array([[0, 1],
        [2, 3]]),
 array([[ 0, 10],
        [20, 30]]))

In [238]:
np.concatenate((arr1, arr2), axis=0) #default 가 axis=0이다

array([[ 0,  1],
       [ 2,  3],
       [ 0, 10],
       [20, 30]])

In [239]:
np.concatenate((arr1, arr2), axis=1)

array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])

In [240]:
#np.c_
np.c_[arr1, arr2]

array([[ 0,  1,  0, 10],
       [ 2,  3, 20, 30]])

# numpy 연습문제

###### 1. 10개의 0벡터 만들고, 4,5번째 index값 1로 하고 (5,2) 행렬 만들기

In [252]:
array1=np.array(range(10))
array1=array1*0
array1[4]=1
array1[5]=1
array1.reshape(5,2)

array([[0, 0],
       [0, 0],
       [1, 1],
       [0, 0],
       [0, 0]])

In [302]:
#답
arr1=np.zeros(10)
arr1[[4,5]]=1
#arr1[4:6]=1
arr1.reshape(5,2)

array([[0., 0.],
       [0., 0.],
       [1., 1.],
       [0., 0.],
       [0., 0.]])

###### 2. 10에서 30까지 2씩 증가하는 vector만들고 다음 list와 요소별 사칙연산을 하여라

In [265]:
a=[1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]

array1=np.arange(10,30,2)
print(array1+a)
print(array1-a)
print(array1*a)
print(array1/a)

[11.  13.1 15.2 17.3 19.4 21.5 23.6 25.7 27.8 29.9]
[ 9.  10.9 12.8 14.7 16.6 18.5 20.4 22.3 24.2 26.1]
[10.  13.2 16.8 20.8 25.2 30.  35.2 40.8 46.8 53.2]
[10.         10.90909091 11.66666667 12.30769231 12.85714286 13.33333333
 13.75       14.11764706 14.44444444 14.73684211]


In [303]:
#답
a=np.array([1, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9])

array1=np.arange(10,30,2)
print(array1+a)
print(array1-a)
print(array1*a)
print(array1/a)

[11.  13.1 15.2 17.3 19.4 21.5 23.6 25.7 27.8 29.9]
[ 9.  10.9 12.8 14.7 16.6 18.5 20.4 22.3 24.2 26.1]
[10.  13.2 16.8 20.8 25.2 30.  35.2 40.8 46.8 53.2]
[10.         10.90909091 11.66666667 12.30769231 12.85714286 13.33333333
 13.75       14.11764706 14.44444444 14.73684211]


###### <1에서 100>까지 10개를 균등하게 분할하여 배열을 만들고, 각각의 합, 평균, 표준편차, 분산, 최소값, 최대값, 누적합, 누적곱 구하기

In [266]:
array1=np.arange(1,100)
array1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34,
       35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51,
       52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68,
       69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85,
       86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [308]:
#답
arr1=np.linspace(1,100,10)
print(arr1.sum())
print(arr1.mean())
print(arr1.std())
print(arr1.var())
print(arr1.min())
print(arr1.max())
print(arr1.cumsum())
print(arr1.cumprod())

505.0
50.5
31.595094555959157
998.25
1.0
100.0
[  1.  13.  36.  70. 115. 171. 238. 316. 405. 505.]
[1.00000000e+00 1.20000000e+01 2.76000000e+02 9.38400000e+03
 4.22280000e+05 2.36476800e+07 1.58439456e+09 1.23582776e+11
 1.09988670e+13 1.09988670e+15]


###### 0에서 10까지 random한 값을 지닌 3x3 실수 행렬을 만들어라

In [309]:
import random
array1= np.random.rand(3,3)
array1

array([[0.88345303, 0.38800968, 0.46116795],
       [0.57688052, 0.83008807, 0.09879978],
       [0.05250607, 0.42681683, 0.56723105]])

In [312]:
#답 rand함수는 0~1까지 값이니까 x10하면 0~10까지 값이 됨
import random
array1= np.random.rand(3,3)
array1*10

array([[6.10178961, 8.24930723, 0.3994231 ],
       [5.42200094, 1.87769226, 6.88452442],
       [5.13686601, 6.21347818, 8.75437241]])

In [318]:
#랜덤이지만, 항상 일정한 값을 리턴하게 하는 법
np.random.seed(42) # 42번째 배열에서만 꺼내주세요
arr1=np.random.rand(3,3)
arr2=arr1*10
arr2

array([[3.74540119, 9.50714306, 7.31993942],
       [5.98658484, 1.5601864 , 1.5599452 ],
       [0.58083612, 8.66176146, 6.01115012]])

###### 0에서 10까지 random한 값을 지닌 3x3 정수 행렬을 만들어라

In [319]:
array1= np.random.randint(0,10,(3,3))
array1

array([[7, 2, 5],
       [4, 1, 7],
       [5, 1, 4]])

###### 5x2행렬을 만들고 standardization (정규화 하여라)

In [293]:
array1=np.arange(0,10).reshape(5,2)
mean=array1.mean()
std=array1.std()

(array1-mean)/std

array([[-1.5666989 , -1.21854359],
       [-0.87038828, -0.52223297],
       [-0.17407766,  0.17407766],
       [ 0.52223297,  0.87038828],
       [ 1.21854359,  1.5666989 ]])

In [331]:
#답
arr1=np.linspace(-1000,1000,5)
arr1=arr1.reshape(-1,5)

arr2=np.linspace(0,10,5)
arr2=arr2.reshape(-1,5)

arr3=np.concatenate((arr1, arr2), axis=0)
arr3=arr3.reshape(5,2)
arr3

array([[-1000. ,  -500. ],
       [    0. ,   500. ],
       [ 1000. ,     0. ],
       [    2.5,     5. ],
       [    7.5,    10. ]])

In [332]:
arr1.std(), arr2.std()

(707.1067811865476, 3.5355339059327378)

In [335]:
arr4=(arr3-arr3.mean(axis=0))/arr3.std(axis=0)
arr4.mean(), arr4.std(), arr4.var()

(-3.2265856653168614e-17, 1.0000000000000002, 1.0000000000000004)

###### 5x2 행렬을 만들고 Min-Max정규화

In [295]:
array1=np.arange(0,10).reshape(5,2)
mean=array1.mean()
std=array1.std()
max_=array1.max()
min_=array1.min()

(array1-min_) / (max_-min_)

array([[0.        , 0.11111111],
       [0.22222222, 0.33333333],
       [0.44444444, 0.55555556],
       [0.66666667, 0.77777778],
       [0.88888889, 1.        ]])